title: ワンライフ・ナビ
description: 愛犬との暮らしを豊かにする総合ガイド
baseurl: "/dog-life-care"
url: "https://tomokazu-hoshi.github.io"

# 記事のURLをスッキリさせる設定
permalink: /posts/:title/

# テーマを指定せず、完全に自作デザインにするための設定（空欄にするのが正解です）
remote_theme: []
